# Generated by Django 3.0 on 2020-03-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_product', '0005_auto_20200320_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
