# Generated by Django 3.0 on 2020-03-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateDiscount',
        ),
    ]
