# Generated by Django 3.0 on 2020-03-25 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0002_delete_datediscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 3, 25, 12, 49, 3, 51750))),
            ],
        ),
    ]
