# Generated by Django 3.0 on 2020-04-03 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_auto_20200403_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datediscount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 18, 43, 18, 913918)),
        ),
    ]
