# Generated by Django 3.0 on 2020-03-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_product', '0002_product_description'),
        ('shopping_cart', '0006_auto_20200315_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='search_product.Product'),
        ),
    ]
