# Generated by Django 3.0 on 2020-03-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0007_auto_20200315_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pay',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
