# Generated by Django 3.0 on 2020-03-22 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_product', '0006_product_discount'),
        ('shopping_cart', '0008_orderitem_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discounted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='new_price',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_product.Product'),
        ),
    ]
