# Generated by Django 3.0 on 2020-03-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0009_auto_20200322_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
