# Generated by Django 3.0 on 2020-03-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0010_auto_20200322_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
