# Generated by Django 3.0 on 2020-03-25 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0011_auto_20200322_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='pay_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 12, 33, 18, 666759)),
        ),
    ]
