# Generated by Django 3.0 on 2020-03-25 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0012_orderitem_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pay_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 12, 49, 3, 39749)),
        ),
    ]
