# Generated by Django 3.0 on 2020-04-02 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0013_auto_20200325_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pay_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 2, 10, 36, 58, 162294)),
        ),
    ]
