# Generated by Django 3.0 on 2020-04-03 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0017_auto_20200403_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='pay_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 18, 32, 46, 975813), null=True),
        ),
    ]
