# Generated by Django 3.0 on 2020-03-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_customer_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
